//QueryDSL 설정
def queryDslVersion = "7.0"
def querydslSrcDir  = layout.buildDirectory.dir("generated/querydsl").get().asFile // build/generated/querydsl
tasks.withType(JavaCompile).configureEach {
    options.getGeneratedSourceOutputDirectory().set(file(querydslSrcDir))
}
sourceSets {
    main {
        java {
            srcDirs += [querydslSrcDir]
        }
    }
}
configurations {
    querydsl.extendsFrom compileClasspath
}

clean {
    delete file(querydslSrcDir)
}

checkstyleMain {
    source = fileTree('src/main/java')  // src/main/java만 검사
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-config-client'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation project(':common')

    //postgreSQL
    runtimeOnly 'org.postgresql:postgresql'

    // Jpa
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    //queryDSL
    implementation("io.github.openfeign.querydsl:querydsl-core:${queryDslVersion}")
    implementation("io.github.openfeign.querydsl:querydsl-jpa:$queryDslVersion")
    annotationProcessor("io.github.openfeign.querydsl:querydsl-apt:$queryDslVersion:jpa")

    //uuid
    implementation 'com.fasterxml.uuid:java-uuid-generator:5.1.0'

    //test
    testImplementation 'org.springframework.security:spring-security-test'

    //retry
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    //RAG
    implementation platform("org.springframework.ai:spring-ai-bom:1.0.0")
    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector'
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    implementation 'org.springframework.ai:spring-ai-advisors-vector-store'

    //security
    implementation 'org.springframework.boot:spring-boot-starter-security'


}
