spring:
  application:
    name: stock-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}?currentSchema=stock_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

#  data:
#    redis:
#      host: ${REDIS_HOST:moni-redis}
#      port: 6379

  data:
    redis:
      cluster:
        nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002
      password: ${REDIS_PASSWORD}
kis:
  app-key: ${KIS_APP_KEY:}
  app-secret: ${KIS_APP_SECRET:}
  ws-url: ws://ops.koreainvestment.com:31000
  rest-url: https://openapi.koreainvestment.com:9443
  mock: false

server:
  port: 19094

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0

kospiUrl: https://new.real.download.dws.co.kr/common/master/kospi_code.mst.zip
kosdaqUrl: https://new.real.download.dws.co.kr/common/master/kosdaq_code.mst.zip
themeUrl: https://new.real.download.dws.co.kr/common/master/idxcode.mst.zip