spring:
  application:
    name: portfolio-service
  config:
    import: optional:configserver:http://config-server:8888

logging:
  file:
    path: /app/logs
  structured:
    format:
      console: logstash
      file: logstash
